#pragma config(Hubs,  S4, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          spinnerA,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          spinnerB,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S4_C2_1,     front_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     front_right,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     back_left,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     back_right,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_1,     lift_left,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_2,     lift_right,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    director1,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_2,    director2,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_3,    lift1,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_4,    lift2,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_5,    door,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//CHANGE ENCODER STUFF
void driveforward(int speed, int distance)
{
	nMotorEncoder[left] = 0;
	nMotorEncoder[right] = 0;
  	motor[front_left] = speed;
  	motor[back_left] = speed;
  	motor[front_right] = speed;
  	motor[back_right] = speed;
	while (abs((nMotorEncoder(left) + nMotorEncoder(right))) < (distance *2)) {}
	motor[front_left] = 0;
	motor[right] = 0;
	wait1Msec(10);
}

void turnleft(int speed, int distance)
{

	//change encoder values
  nMotorEncoder[left] = 0;
  motor[front_left] = speed;
  motor[back_left] = speed;
  while (abs(nMotorEncoder(left)) < distance) {}
  motor[front_left] = 0;
  motor[back_left] = 0;
  wait1Msec(10);
}

void turnright(int speed, int distance)
{
	nMotorEncoder[right] = 0;
    motor[front_right] = speed;
    motor[back_right] = speed;
    while (abs(nMotorEncoder(right)) < distance) {}
    motor[front_right] = 0;
	motor[back_right] = 0;
    wait1Msec(10);
}

task main()
{
	waitForStart();
}