#pragma config(Hubs,  S4, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          spinnerA,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          spinnerB,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     front_right,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     front_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_1,     back_right,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_2,     back_left,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C2_1,    hook,                 tServoStandard)
#pragma config(Servo,  srvo_S4_C2_2,    hook,                 tServoStandard)
#pragma config(Servo,  srvo_S4_C2_3,    spinner1,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C2_4,    spinner2,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C2_5,    door,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "menu.h"
#include "tasks.h"

/*
	distance constants
*/
#define RAMP_DISTANCE 0


//implement state machine for autonomous
void runAutonomous(int instructions[]) {
	bool done = false;

	while (!done) {

		int i = 0;

		int state = instructions[i];
		int nextState = instructions[i+1];

		if (state == RAMP_STARTING) {
			
		}

	}
}

task main()
{

	int instructions[4]; //will hold instructions for running autonomous

	eraseDisplay();

	displayOptionsMenu(instructions); //display options menu

	waitForStart();

	runAutonomous(instructions);

}
