#pragma config(Hubs,  S4, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Sensor, S3,     color,          sensorColorNxtFULL)
#pragma config(Motor,  motorB,          spinnerA,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          spinnerB,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     front_right,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     front_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_1,     back_right,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_2,     back_left,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C2_1,    hook1,                tServoStandard)
#pragma config(Servo,  srvo_S4_C2_2,    hook2,                tServoStandard)
#pragma config(Servo,  srvo_S4_C2_3,    spinner1,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C2_4,    spinner2,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C2_5,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S4_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "utilities.h"
#include "JoystickDriver.c"
#include "hitechnic-irseeker-v2.h"

task main()
{


	waitForStart();
	servo[hook1] = HOOK_UP+15;
  servo[hook2] = 180-HOOK_UP;
  servo[door] = DOOR_UP;
	while (SensorValue[sonar] > 15) {
		driveBackward(50, -1);
		nxtDisplayBigTextLine(3, "%d", nMotorEncoder[front_left]);
	}
	stop();
	servo[hook1] = HOOK_DOWN+20;
  servo[hook2] = HOOK_DOWN-50;
	raiseLift(LIFT_MEDIUM);
	depositBall();
	lowerLift(LIFT_MEDIUM);
	point_turn(100, 2000, -1);
	servo[hook1] = HOOK_UP+15;
  servo[hook2] = 180-HOOK_UP;
  wait10Msec(100);
	point_turn(100, 1650, 1);
   while (SensorValue[sonar] > 15) {
		driveBackward(50, -1);
		nxtDisplayBigTextLine(3, "%d", nMotorEncoder[front_left]);
	}
	stop();
	runCollector();
	raiseLift(LIFT_LARGE);
	depositBall();
	lowerLift(LIFT_LARGE);


}
