#pragma config(Hubs,  S4, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          spinnerA,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          spinnerB,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S4_C2_1,     b_right,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     f_right,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     f_left,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     b_left,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    director1,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_2,    director2,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_3,    lift1,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_4,    lift2,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_5,    door,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define ROT_CONST 0.39
#define DRIVE_CONST 0.78

/*
Drive configuration:

	   Front
	  _______
  1 O|       |O 2
	 |       |
	 |       |
	 |       |
  3 O|_______|O 4

  1: cos(theta-PI/4)
  2: cos(theta+PI/4)
  3: cos(theta+PI/4)
  4: cos(theta-PI/4)

  Positive rotation is forward
*/
void drive()
{
	getJoystickSettings(joystick);

	int threshold = 20; //minimum value of joystick before activating drive

	int x = joystick.joy1_x1;
	int y = -1*joystick.joy1_y1; //y is inverted

	int rot = joystick.joy1_x2;
	int rotL;
	int rotR;

	float angle = atan2(y,x);
	float length = sqrt(pow(x,2)+pow(y,2));

	if(length < threshold){
		length = 0;
  	}

	if (abs(rot) < threshold) {
		rotL = 0;
		rotR = 0;
	}

	else {
		rotL = ROT_CONST * rot;
		rotR = ROT_CONST * rot;
	}

	int f_left = DRIVE_CONST * cos(angle-(PI/4)) * length + rotL;
	int f_right = DRIVE_CONST * cos(angle+(PI/4)) * length + rotL;
	int b_left = DRIVE_CONST * cos(angle+(PI/4)) * length + rotR;
	int b_right = DRIVE_CONST * cos(angle-(PI/4)) * length + rotR;

	motor[f_left] = f_left;
	motor[f_right] = f_right;
	motor[b_left] = b_left;
	motor[b_right] = b_right;

	//nxtDisplayBigTextLine(3, "X: %d Y: %d", x, y);
}

task main()
{
	while (true) {
		drive();
	}
}
