#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     front_right,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     front_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     back_right,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     back_left,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void drive()
{
	getJoystickSettings(joystick);

	int threshold = 20;

	int x = joystick.joy1_x1;
	int y = joystick.joy1_y1;

	if (abs(y) > threshold ) {
		if (y < 0) {
			motor[front_right] = 100;
			motor[front_left] = 100;
		  motor[back_right] = 100;
		  motor[back_left] = 100;
		}
		else if (y > 0) {
			motor[front_right] = -100;
			motor[front_left] = -100;
		  motor[back_right] = -100;
		  motor[back_left] = -100;
		}
	}
	else if (abs(x) > threshold ) {
		if (x > 0) {
			motor[front_right] = -100;
			motor[front_left] = 100;
			motor[back_right] = 100;
			motor[back_left] = -100;
		}
		else if (x < 0) {
			motor[front_right] = 100;
			motor[front_left] = -100;
			motor[back_right] = -100;
			motor[back_left] = 100;
		}
	}
	else {
		motor[front_right] = 0;
		motor[front_left] = 0;
		motor[back_right] = 0;
		motor[back_left] = 0;
	}

	nxtDisplayBigTextLine(3, "X: %d Y: %d", x, y);
}

task main()
{
	while (true) {
		//drive();
	  motor[front_left]
	}
}
