#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     front_right,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     front_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     back_right,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     back_left,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void drive()
{
	getJoystickSettings(joystick);

	int threshold = 20;

	int x = joystick.joy1_x1;
	int y = -1*joystick.joy1_y1;

	float angle = 0;

	if(y>0){
		angle = atan((float)y/(float)x);
	}else{
		angle = PI + atan((float)y/(float)x);
  }


	float length = sqrt(pow(x,2)+pow(y,2));

	if(length < 20){
		length = 0;
  }

	int f_left = -100*cos((PI/4)-angle)*length;
	int f_right = 100*cos((PI/4)+angle)*length;
	int b_left = 100*cos((PI/4)+angle)*length;
	int b_right = 100*cos((PI/4)-angle)*length;

	motor[front_left] = f_left;
	motor[front_right] = f_right;
	motor[back_left] = b_left;
	motor[back_right] = b_right;

	//nxtDisplayBigTextLine(3, "X: %d Y: %d", x, y);
}

task main()
{
	while (true) {
		drive();
	}
}
