#pragma config(Hubs,  S4, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          spinnerA,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          spinnerB,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     front_right,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     front_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_1,     back_right,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_2,     back_left,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C2_1,    hook1,                tServoStandard)
#pragma config(Servo,  srvo_S4_C2_2,    hook2,                tServoStandard)
#pragma config(Servo,  srvo_S4_C2_3,    spinner1,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C2_4,    spinner2,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C2_5,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S4_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "hitechnic-superpro.h"
#include "utilities.h"

void TankDrive(float adjust)
{
	getJoystickSettings(joystick);			 // Allows use of Joysticks

	int leftspeed =  adjust * joystick.joy1_y1;
 	int rightspeed =  adjust * joystick.joy1_y2;
  	int threshold = 20;


	if (abs(leftspeed) < threshold) {
		motor[front_left] = 0;
		motor[back_left] = 0;
	}
	else {
		motor[front_left] = leftspeed;
		motor[back_left] = leftspeed;
	}

	if (abs(rightspeed) < threshold) {
		motor[front_right] = 0;
		motor[back_right] = 0;
	}
	else {
		motor[front_right] = -rightspeed;
		motor[back_right] = -rightspeed;
	}
}

task main()
{
	motor[spinnerA] = 0;
  	motor[spinnerB] = 0;

 	motor[lift] = 0;

	servo[spinner1] = 128;
	servo[spinner2] = 128;

	servo[door] = DOOR_UP;

	bool hookSwitcher = false;
	bool hookPressed = false;

	bool doorSwitcher = false;
	bool doorPressed = false;

	bool adjustSwitcher = false;
	bool adjustPressed = false;

	int threshold = 20;

	getJoystickSettings(joystick);

	HTSPBsetupIO(HTSPB, 0b00001111);
	clearTimer(T1);
	int sonarDistance = 0;

	while (true) {

		TankDrive(1.0);

		//stops spinners
		if (joy1Btn(05)) {

			//motor[spinnerA] = 0;
			//motor[spinnerB] = 0;

			motor[collector] = 0;

			servo[spinner1] = 128;
			servo[spinner2] = 128;
		}

		//spins spinner
		if (joy1Btn(07)) {
			//motor[spinnerA] = -100;
			//motor[spinnerB] = -100;

			motor[collector] = 100;

			motor[spinnerA] = -100;
			motor[spinnerB] = -100;

			servo[spinner1] = 100;
			servo[spinner2] = 200;
		}

		//raise or lower lift (controller 2)
		if (abs(joystick.joy2_y2) > threshold) {
			motor[lift] = -joystick.joy2_y2;
		}
		//lift up (controller 1)
		else if (joy1Btn(04) && abs(joystick.joy2_y2) < threshold) {
			motor[lift] = -100;
		}
		//lift down (controller 1)
		else if (joy1Btn(02) && abs(joystick.joy2_y2) < threshold) {
			motor[lift] = 100;
		}
		//lift stopped
		else {
			motor[lift] = 0;
		}

		if ((joy1Btn(03) || joy2Btn(03)) && !doorPressed) {
			if (doorSwitcher){
			   doorSwitcher = false;
		  	}
		  	else {
		     	doorSwitcher = true;
		  	}
	  		doorPressed = true;
		}

		if (!(joy1Btn(03) || joy2Btn(03)) && doorPressed) {
    		doorPressed = false;
    	}

		if (!doorSwitcher) {
     		servo[door] = DOOR_DOWN;
		}
    	else {
    		servo[door] = DOOR_UP;
    	}

		if (joy1Btn(06)) {
     		servo[hook1] = HOOK_UP+15;
     		servo[hook2] = 180-HOOK_UP;
		}
    	if (joy1Btn(08)) {
    		servo[hook1] = HOOK_DOWN+20;
    		servo[hook2] = HOOK_DOWN-50;
    	}

    	/*
    	if (joy2Btn(04)) {
    		raiseLift(LIFT_CENTER);
    	}

    	if (joy2Btn(01)) {
    		raiseLift(LIFT_LARGE);
    	}

    	if (joy2Btn(02)) {
    		raiseLift(LIFT_MEDIUM);
    	} */
    	//if(time10[T1]>9000){

			if(SensorValue[sonar] > 30){
				HTSPBwriteIO(HTSPB,0b00000000);
			}
			if(SensorValue[sonar] > 24 && SensorValue[sonar] <= 30){
				HTSPBwriteIO(HTSPB,0b00000001);
			}
			if(SensorValue[sonar] >= 21 && SensorValue[sonar] <= 23){
				HTSPBwriteIO(HTSPB,0b00000011);
			}
			if(SensorValue[sonar] > 10 && SensorValue[sonar] < 21){
				HTSPBwriteIO(HTSPB,0b00000111);
			}
			if(SensorValue[sonar] <= 10){
				HTSPBwriteIO(HTSPB,0b00001111);
			}
	}
}
