#pragma config(Hubs,  S4, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          spinnerA,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          spinnerB,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     front_right,   tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S4_C3_2,     front_left,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S4_C4_1,     back_right,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S4_C4_2,     back_left,     tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S4_C2_1,    hook1,                tServoStandard)
#pragma config(Servo,  srvo_S4_C2_2,    hook2,                tServoStandard)
#pragma config(Servo,  srvo_S4_C2_3,    spinner1,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C2_4,    spinner2,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C2_5,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S4_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "utilities.h"
#include "JoystickDriver.c"

task main()
{

  waitForStart();


	//clamp();

	/*
	raiseLift(0);
	depositBall();
	*/


	/*
	point_turn(50, 2000, 1);
	driveBackward(50, 600);
	point_turn(50, 3200, -1);
	driveBackward(50, 5000);
	*/

}
