#pragma config(Hubs,  S4, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          spinnerA,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          spinnerB,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     front_right,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     front_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_1,     back_right,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_2,     back_left,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C2_1,    hook1,                tServoStandard)
#pragma config(Servo,  srvo_S4_C2_2,    hook2,                tServoStandard)
#pragma config(Servo,  srvo_S4_C2_3,    director1,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C2_4,    director2,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C2_5,    door,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void TankDrive()
{
	getJoystickSettings(joystick);			 // Allows use of Joysticks

	int leftspeed = 0.008 * joystick.joy1_y1;
 	int rightspeed = -0.008 * joystick.joy1_y2;
  int threshold = 20;

	if (abs(leftspeed) < threshold) {
		motor[front_left] = 0;
		motor[back_left] = 0;
	}
	else {
		motor[front_left] = leftspeed;
		motor[back_left] = leftspeed;
	}

	if (abs(rightspeed) < threshold) {
		motor[front_right] = 0;
		motor[back_right] = 0;
	}
	else {
		motor[front_right] = rightspeed;
		motor[back_right] = rightspeed;
	}

	nxtDisplayBigTextLine(3, "leftspeed: %d rightspeed: %d", leftspeed, rightspeed);
}

void HoloDrive()
{
	getJoystickSettings(joystick);

	int threshold = 20; //minimum value of joystick before activating drive

	int x = joystick.joy1_x1;
	int y = -1*joystick.joy1_y1; //y is inverted

	float angle = atan2(y,x);

	float length = sqrt(pow(x,2)+pow(y,2));

	if (length < threshold){
		length = 0;
  }

	int f_left = 0.78*cos(angle+(PI/4)+(PI/2))*length;
	int f_right = -0.78*cos(angle-(PI/4)+(PI/2))*length;
	int b_left = 0.90*cos(angle-(PI/4)+(PI/2))*length;
	int b_right = -0.90*cos(angle+(PI/4)+(PI/2))*length;

	motor[front_left] = f_left;
	motor[front_right] = f_right;
	motor[back_left] = b_left;
	motor[back_right] = b_right;

	//nxtDisplayBigTextLine(3, "X: %d Y: %d", x, y);
}

task main()
{

	while (true) {
		HoloDrive();
		}
}
